POST http://127.0.0.1:8000/user-service/api/users
Content-Type: application/json

{
	"email" : "black@gmail.com",
	"name" : "black",
	"password" : "1234!@#"
}

###

GET http://127.0.0.1:8000/user-service/api/users

###

GET http://127.0.0.1:8000/user-service/api/users/a4b80239-2a69-4146-870f-9423b541526e
