POST http://127.0.0.1:8000/user-service/api/users
Content-Type: application/json

{
	"email" : "black@app.com",
	"name" : "black",
	"password" : "1234!@#"
}

###

POST http://127.0.0.1:8000/user-service/login
Content-Type: application/json

{
	"email" : "black@app.com",
	"password" : "1234!@#"
}

###

GET http://127.0.0.1:8000/user-service/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmMTFiYjYwMi1kNDljLTRmYjctYjNmYy1mMjYxZTIyYWMwNTkiLCJleHAiOjE2NDI5MzIyMTZ9.3zVuhGpTG_ehiGT9VDdNJQQH48reoeN0XXvGA-7tP0N1GCNci4kZJaodXUt_BjVm8hhVMEouiON7tp2feEGYGA

###

GET http://127.0.0.1:8000/user-service/api/users/a4b80239-2a69-4146-870f-9423b541526e
