POST http://127.0.0.1:8000/user-service/api/users
Content-Type: application/json

{
	"email" : "black@apple.com",
	"name" : "black",
	"password" : "1234!@#"
}

###

GET http://127.0.0.1:8000/user-service/api/users
