server:
  port: 8000

eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
#          uri: http://127.0.0.1:8001/
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            # first-service(id) 어플(http://127.0.0.1:8001/)의 end point(uri) 를 가기 위해서는
            # gateway server host:port + predicates + client server path 조합으로 요청을 보내야 함
            # (ex. http://127.0.0.1:8000/order-service/api/orders)
          filters:
            - CustomFilter
#            - AddRequestHeader=order-request, order-request-header2
#            - AddResponseHeader=order-response, order-response-header2
        - id: second-service
#          uri: http://127.0.0.1:8002/
          uri: lb://user-service
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}
        - id: second-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Logging Filter
#                preLogger: true
#                postLogger: true
#            - AddRequestHeader=user-request, user-request-header2
#            - AddResponseHeader=user-response, user-response-header2
        - id: third-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1