server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://127.0.0.1:8001/
          predicates:
            - Path=/order-service/**
            # first-service(id) 어플(http://127.0.0.1:8001/)의 end point(uri) 를 가기 위해서는
            # gateway server host:port + predicates + client server path 조합으로 요청을 보내야 함
            # (ex. http://127.0.0.1:8000/order-service/api/orders)
          filters:
            - AddRequestHeader=order-request, order-request-header2
            - AddResponseHeader=order-response, order-response-header2
        - id: second-service
          uri: http://127.0.0.1:8002/
          predicates:
            - Path=/user-service/**
          filters:
            - AddRequestHeader=user-request, user-request-header2
            - AddResponseHeader=user-response, user-response-header2
